name: snap-geo
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - affine=2.3.1
  - alsa-lib=1.2.7.2
  - antlr-python-runtime=4.7.2
  - anyio=3.6.2
  - appdirs=1.4.4
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - astroid=2.12.13
  - asttokens=2.1.0
  - attrs=22.1.0
  - babel=2.11.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - beautifulsoup4=4.11.1
  - black=22.10.0
  - bleach=5.0.1
  - blosc=1.21.1
  - bokeh=2.4.3
  - boltons=21.0.0
  - boost-cpp=1.74.0
  - bottleneck=1.3.5
  - branca=0.6.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.9.24
  - cairo=1.16.0
  - cartopy=0.20.2
  - certifi=2022.9.24
  - cf-python=3.13.1
  - cf-units=3.1.1
  - cf_xarray=0.7.5
  - cfdm=1.9.0.4
  - cffi=1.15.1
  - cfitsio=4.1.0
  - cftime=1.6.2
  - cfunits=3.3.5
  - charset-normalizer=2.1.1
  - click=8.1.3
  - click-plugins=1.1.1
  - cligj=0.7.2
  - cloudpickle=2.2.0
  - colorama=0.4.6
  - colorcet=3.0.1
  - comm=0.1.0
  - contourpy=1.0.6
  - cryptography=38.0.3
  - curl=7.86.0
  - cycler=0.11.0
  - cytoolz=0.12.0
  - dask=2022.11.1
  - dask-core=2022.11.1
  - dbus=1.13.6
  - debugpy=1.6.3
  - decorator=5.1.1
  - defusedxml=0.7.1
  - dill=0.3.6
  - distlib=0.3.6
  - distributed=2022.11.1
  - entrypoints=0.4
  - esmf=8.2.0
  - esmpy=8.2.0
  - executing=1.2.0
  - expat=2.5.0
  - filelock=3.8.0
  - fiona=1.8.21
  - flit-core=3.8.0
  - folium=0.13.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.1
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.38.0
  - freetype=2.12.1
  - freexl=1.0.6
  - fsspec=2022.11.0
  - gdal=3.4.3
  - geopandas=0.12.1
  - geopandas-base=0.12.1
  - geos=3.10.2
  - geotiff=1.7.1
  - gettext=0.21.1
  - giflib=5.2.1
  - glib=2.74.1
  - glib-tools=2.74.1
  - gst-plugins-base=1.20.3
  - gstreamer=1.20.3
  - hdf4=4.2.15
  - hdf5=1.12.1
  - heapdict=1.0.1
  - holoviews=1.15.2
  - hvplot=0.8.1
  - icu=69.1
  - idna=3.4
  - importlib-metadata=5.0.0
  - importlib_metadata=5.0.0
  - importlib_resources=5.10.0
  - intake=0.6.6
  - ipykernel=6.18.0
  - ipython=8.6.0
  - ipython_genutils=0.2.0
  - ipywidgets=8.0.2
  - iris=3.3.0
  - isort=5.10.1
  - jedi=0.18.2
  - jinja2=3.1.2
  - joblib=1.2.0
  - jpeg=9e
  - json-c=0.16
  - json5=0.9.5
  - jsonpickle=2.2.0
  - jsonschema=4.17.0
  - jupyter_client=7.3.4
  - jupyter_core=5.0.0
  - jupyter_server=1.23.3
  - jupyterlab=3.5.0
  - jupyterlab_pygments=0.2.2
  - jupyterlab_server=2.16.3
  - jupyterlab_widgets=3.0.3
  - kealib=1.4.15
  - keyutils=1.6.1
  - kiwisolver=1.4.4
  - krb5=1.19.3
  - lazy-object-proxy=1.8.0
  - lcms2=2.14
  - ld_impl_linux-64=2.39
  - lerc=4.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libclang=13.0.1
  - libcurl=7.86.0
  - libdap4=3.20.6
  - libdeflate=1.14
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.10
  - libffi=3.4.2
  - libgcc-ng=12.2.0
  - libgdal=3.4.3
  - libgfortran-ng=12.2.0
  - libgfortran5=12.2.0
  - libglib=2.74.1
  - libgomp=12.2.0
  - libiconv=1.17
  - libkml=1.3.0
  - liblapack=3.9.0
  - libllvm11=11.1.0
  - libllvm13=13.0.1
  - libnetcdf=4.8.1
  - libnghttp2=1.47.0
  - libnsl=2.0.0
  - libogg=1.3.4
  - libopenblas=0.3.21
  - libopus=1.3.1
  - libpng=1.6.39
  - libpq=14.2
  - librttopo=1.1.0
  - libsodium=1.0.18
  - libspatialindex=1.9.3
  - libspatialite=5.0.1
  - libsqlite=3.40.0
  - libssh2=1.10.0
  - libstdcxx-ng=12.2.0
  - libtiff=4.4.0
  - libuuid=2.32.1
  - libvorbis=1.3.7
  - libwebp-base=1.2.4
  - libxcb=1.13
  - libxkbcommon=1.0.3
  - libxml2=2.9.12
  - libzip=1.9.2
  - libzlib=1.2.13
  - llvmlite=0.39.1
  - locket=1.0.0
  - lz4=4.0.2
  - lz4-c=1.9.3
  - mapclassify=2.4.3
  - markdown=3.4.1
  - markupsafe=2.1.1
  - matplotlib=3.6.2
  - matplotlib-base=3.6.2
  - matplotlib-inline=0.1.6
  - mccabe=0.7.0
  - mistune=2.0.4
  - msgpack-python=1.0.4
  - munch=2.5.0
  - munkres=1.1.4
  - mypy_extensions=0.4.3
  - mysql-common=8.0.31
  - mysql-libs=8.0.31
  - nbclassic=0.4.8
  - nbclient=0.7.0
  - nbconvert=7.2.5
  - nbconvert-core=7.2.5
  - nbconvert-pandoc=7.2.5
  - nbformat=5.7.0
  - ncurses=6.3
  - nest-asyncio=1.5.6
  - netcdf-flattener=1.2.0
  - netcdf-fortran=4.5.4
  - netcdf4=1.6.0
  - networkx=2.8.8
  - notebook=6.5.2
  - notebook-shim=0.2.2
  - nspr=4.32
  - nss=3.78
  - numba=0.56.4
  - numpy=1.23.5
  - openjpeg=2.5.0
  - openssl=3.0.7
  - packaging=21.3
  - pandas=1.5.2
  - pandoc=2.19.2
  - pandocfilters=1.5.0
  - panel=0.14.1
  - param=1.12.2
  - parso=0.8.3
  - partd=1.3.0
  - pathspec=0.10.2
  - patsy=0.5.3
  - pcre=8.45
  - pcre2=10.40
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.2.0
  - pint=0.20.1
  - pip=22.3.1
  - pipenv=2022.11.11
  - pixman=0.40.0
  - pkgutil-resolve-name=1.3.10
  - platformdirs=2.5.2
  - poppler=22.04.0
  - poppler-data=0.4.11
  - postgresql=14.2
  - proj=9.0.0
  - prometheus_client=0.15.0
  - prompt-toolkit=3.0.33
  - psutil=5.9.4
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pyct=0.4.6
  - pyct-core=0.4.6
  - pygments=2.13.0
  - pylint=2.15.6
  - pyopenssl=22.1.0
  - pyparsing=3.0.9
  - pyproj=3.3.1
  - pyqt=5.12.3
  - pyrsistent=0.19.2
  - pyshp=2.3.1
  - pysocks=1.7.1
  - python=3.9.15
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python-xxhash=3.0.0
  - python_abi=3.9
  - pytz=2022.6
  - pyviz_comms=2.2.1
  - pyyaml=6.0
  - pyzmq=24.0.1
  - qt=5.12.9
  - rasterio=1.2.10
  - rasterstats=0.17.0
  - readline=8.1.2
  - requests=2.28.1
  - rioxarray=0.13.1
  - rtree=1.0.1
  - scikit-learn=1.1.3
  - scipy=1.9.3
  - seaborn=0.12.1
  - seaborn-base=0.12.1
  - send2trash=1.8.0
  - setuptools=65.5.1
  - shapely=1.8.2
  - simplejson=3.18.0
  - six=1.16.0
  - snappy=1.1.9
  - sniffio=1.3.0
  - snuggs=1.4.7
  - sortedcontainers=2.4.0
  - soupsieve=2.3.2.post1
  - sparse=0.13.0
  - sqlite=3.40.0
  - stack_data=0.6.1
  - statsmodels=0.13.5
  - tblib=1.7.0
  - terminado=0.17.0
  - threadpoolctl=3.1.0
  - tiledb=2.8.3
  - tinycss2=1.2.1
  - tk=8.6.12
  - tomli=2.0.1
  - tomlkit=0.11.6
  - toolz=0.12.0
  - tornado=6.1
  - tqdm=4.64.1
  - traitlets=5.5.0
  - typing=3.10.0.0
  - typing-extensions=4.4.0
  - typing_extensions=4.4.0
  - tzcode=2022f
  - tzdata=2022f
  - udunits2=2.2.28
  - unicodedata2=15.0.0
  - urllib3=1.26.11
  - virtualenv=20.16.7
  - virtualenv-clone=0.5.4
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=1.4.2
  - wheel=0.38.4
  - widgetsnbextension=4.0.3
  - wrapt=1.14.1
  - wrf-python=1.3.4.1
  - xarray=2022.11.0
  - xclim=0.37.0
  - xerces-c=3.2.3
  - xesmf=0.6.3
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.7.2
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xxhash=0.8.0
  - xyzservices=2022.9.0
  - xz=5.2.6
  - yaml=0.2.5
  - zeromq=4.3.4
  - zict=2.2.0
  - zipp=3.10.0
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
    - pyqt5-sip==4.19.18
    - pyqtchart==5.12
    - pyqtwebengine==5.12.1
