name: snap-geo
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - accessible-pygments=0.0.5
  - affine=2.4.0
  - aiohttp=3.9.5
  - aiosignal=1.3.1
  - alabaster=0.7.16
  - alsa-lib=1.2.9
  - annotated-types=0.7.0
  - ansicolors=1.1.8
  - anyio=4.4.0
  - aom=3.9.1
  - appdirs=1.4.4
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - asciitree=0.3.3
  - asttokens=2.4.1
  - async-lru=2.0.4
  - attr=2.5.1
  - attrs=23.2.0
  - aws-c-auth=0.7.7
  - aws-c-cal=0.6.9
  - aws-c-common=0.9.8
  - aws-c-compression=0.2.17
  - aws-c-event-stream=0.3.2
  - aws-c-http=0.7.14
  - aws-c-io=0.13.36
  - aws-c-mqtt=0.9.10
  - aws-c-s3=0.4.1
  - aws-c-sdkutils=0.1.12
  - aws-checksums=0.1.17
  - aws-crt-cpp=0.24.7
  - aws-sdk-cpp=1.11.182
  - babel=2.14.0
  - beautifulsoup4=4.12.3
  - black=24.4.2
  - bleach=6.1.0
  - blosc=1.21.5
  - bokeh=3.4.2
  - boltons=24.0.0
  - boost-cpp=1.78.0
  - bottleneck=1.4.0
  - branca=0.7.2
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.32.3
  - c-blosc2=2.12.0
  - ca-certificates=2024.7.4
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cads-api-client=1.1.0
  - cairo=1.16.0
  - cartopy=0.23.0
  - cdsapi=0.7.0
  - certifi=2024.7.4
  - cf-python=3.16.1
  - cf_xarray=0.9.4
  - cfdm=1.11.1.0
  - cffi=1.16.0
  - cfgrib=0.9.14.0
  - cfitsio=4.2.0
  - cftime=1.6.4
  - cfunits=3.3.7
  - charls=2.4.2
  - charset-normalizer=3.3.2
  - click=8.1.7
  - click-plugins=1.1.1
  - cligj=0.7.2
  - clisops=0.13.0
  - cloudpickle=3.0.0
  - colorama=0.4.6
  - colorcet=3.1.0
  - comm=0.2.2
  - contourpy=1.2.1
  - cryptography=42.0.2
  - curl=8.4.0
  - cycler=0.12.1
  - cytoolz=0.12.3
  - dask=2024.7.1
  - dask-core=2024.7.1
  - dask-expr=1.1.9
  - dask-jobqueue=0.8.5
  - dataclasses=0.8
  - datashader=0.16.3
  - dav1d=1.2.1
  - dbus=1.13.6
  - debugpy=1.8.2
  - decorator=5.1.1
  - defusedxml=0.7.1
  - distributed=2024.7.1
  - docopt=0.6.2
  - docutils=0.20.1
  - eccodes=2.31.0
  - entrypoints=0.4
  - esmf=8.4.2
  - esmpy=8.4.2
  - exceptiongroup=1.2.2
  - executing=2.0.1
  - expat=2.6.2
  - fasteners=0.17.3
  - fastprogress=1.0.3
  - findlibs=0.0.5
  - fiona=1.9.4
  - flox=0.9.8
  - folium=0.17.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.53.1
  - fqdn=1.5.1
  - freeglut=3.2.2
  - freetype=2.12.1
  - freexl=1.0.6
  - frozenlist=1.4.1
  - fsspec=2024.6.1
  - gdal=3.7.0
  - geopandas=0.14.4
  - geopandas-base=0.14.4
  - geos=3.11.2
  - geotiff=1.7.1
  - gettext=0.22.5
  - gettext-tools=0.22.5
  - gflags=2.2.2
  - giflib=5.2.2
  - glib=2.78.1
  - glib-tools=2.78.1
  - globus-cli=3.29.0
  - globus-sdk=3.41.0
  - glog=0.6.0
  - graphite2=1.3.13
  - greenlet=3.0.3
  - gst-plugins-base=1.22.5
  - gstreamer=1.22.5
  - h11=0.14.0
  - h2=4.1.0
  - h5netcdf=1.3.0
  - h5py=3.9.0
  - harfbuzz=7.3.0
  - hdf4=4.2.15
  - hdf5=1.14.1
  - holoviews=1.19.1
  - hpack=4.0.0
  - httpcore=1.0.5
  - httpx=0.27.0
  - hvplot=0.10.0
  - hyperframe=6.0.1
  - icu=72.1
  - idna=3.7
  - imagecodecs=2023.9.4
  - imageio=2.34.2
  - imagesize=1.4.1
  - importlib-metadata=8.2.0
  - importlib_metadata=8.2.0
  - importlib_resources=6.4.0
  - iniconfig=2.0.0
  - intake=0.7.0
  - intake-esm=2024.2.6
  - intake-xarray=0.7.0
  - ipykernel=6.29.5
  - ipyleaflet=0.19.2
  - ipython=8.26.0
  - ipywidgets=8.1.3
  - isoduration=20.11.0
  - jasper=4.0.0
  - jedi=0.19.1
  - jinja2=3.1.4
  - jmespath=1.0.1
  - joblib=1.4.2
  - json-c=0.16
  - json5=0.9.25
  - jsonpickle=3.2.2
  - jsonpointer=3.0.0
  - jsonschema=4.23.0
  - jsonschema-specifications=2023.12.1
  - jsonschema-with-format-nongpl=4.23.0
  - jupyter-book=1.0.2
  - jupyter-cache=1.0.0
  - jupyter-lsp=2.2.5
  - jupyter_client=8.6.2
  - jupyter_core=5.7.2
  - jupyter_events=0.10.0
  - jupyter_leaflet=0.19.2
  - jupyter_server=2.14.2
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.2.4
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - jupyterlab_widgets=3.0.11
  - jxrlib=1.1
  - kealib=1.5.1
  - keyutils=1.6.1
  - kiwisolver=1.4.5
  - krb5=1.21.2
  - lame=3.100
  - latexcodec=2.0.1
  - lazy_loader=0.4
  - lcms2=2.15
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libabseil=20230802.1
  - libaec=1.1.3
  - libarchive=3.6.2
  - libarrow=14.0.1
  - libarrow-acero=14.0.1
  - libarrow-dataset=14.0.1
  - libarrow-flight=14.0.1
  - libarrow-flight-sql=14.0.1
  - libarrow-gandiva=14.0.1
  - libarrow-substrait=14.0.1
  - libasprintf=0.22.5
  - libasprintf-devel=0.22.5
  - libavif16=1.1.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcap=2.69
  - libcblas=3.9.0
  - libclang=15.0.7
  - libclang13=15.0.7
  - libcrc32c=1.1.2
  - libcups=2.3.3
  - libcurl=8.4.0
  - libdeflate=1.18
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.6.2
  - libffi=3.4.2
  - libflac=1.4.3
  - libgcc-ng=14.1.0
  - libgcrypt=1.11.0
  - libgdal=3.7.0
  - libgettextpo=0.22.5
  - libgettextpo-devel=0.22.5
  - libgfortran-ng=14.1.0
  - libgfortran5=14.1.0
  - libglib=2.78.1
  - libglu=9.0.0
  - libgomp=14.1.0
  - libgoogle-cloud=2.12.0
  - libgpg-error=1.50
  - libgrpc=1.59.3
  - libiconv=1.17
  - libidn2=2.3.7
  - libjpeg-turbo=2.1.5.1
  - libkml=1.3.0
  - liblapack=3.9.0
  - libllvm14=14.0.6
  - libllvm15=15.0.7
  - libnetcdf=4.9.2
  - libnghttp2=1.58.0
  - libnl=3.10.0
  - libnsl=2.0.1
  - libogg=1.3.5
  - libopenblas=0.3.27
  - libopus=1.3.1
  - libparquet=14.0.1
  - libpng=1.6.43
  - libpq=15.4
  - libprotobuf=4.24.4
  - libre2-11=2023.09.01
  - librttopo=1.1.0
  - libsndfile=1.2.2
  - libsodium=1.0.18
  - libspatialindex=2.0.0
  - libspatialite=5.0.1
  - libsqlite=3.46.0
  - libssh2=1.11.0
  - libstdcxx-ng=14.1.0
  - libsystemd0=255
  - libthrift=0.19.0
  - libtiff=4.5.1
  - libudunits2=2.2.28
  - libunistring=0.9.10
  - libutf8proc=2.8.0
  - libuuid=2.38.1
  - libvorbis=1.3.7
  - libwebp-base=1.4.0
  - libxcb=1.15
  - libxkbcommon=1.6.0
  - libxml2=2.11.5
  - libxslt=1.1.37
  - libzip=1.10.1
  - libzlib=1.2.13
  - libzopfli=1.0.3
  - linkify-it-py=2.0.3
  - llvmlite=0.43.0
  - locket=1.0.0
  - loguru=0.7.2
  - lxml=4.9.3
  - lz4=4.3.3
  - lz4-c=1.9.4
  - lzo=2.10
  - mapclassify=2.7.0
  - markdown=3.6
  - markdown-it-py=3.0.0
  - markupsafe=2.1.5
  - matplotlib=3.9.1
  - matplotlib-base=3.9.1
  - matplotlib-inline=0.1.7
  - mdit-py-plugins=0.4.1
  - mdurl=0.1.2
  - mistune=3.0.2
  - mpg123=1.32.6
  - msgpack-python=1.0.8
  - multidict=6.0.5
  - multipledispatch=0.6.0
  - multiurl=0.3.1
  - munch=4.0.0
  - munkres=1.1.4
  - mypy_extensions=1.0.0
  - mysql-common=8.0.33
  - mysql-libs=8.0.33
  - myst-nb=1.1.1
  - myst-parser=2.0.0
  - nbclient=0.10.0
  - nbconvert=7.16.4
  - nbconvert-core=7.16.4
  - nbconvert-pandoc=7.16.4
  - nbformat=5.10.4
  - nc-time-axis=1.4.1
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - netcdf-flattener=1.2.0
  - netcdf-fortran=4.6.1
  - netcdf4=1.6.4
  - networkx=3.3
  - notebook=7.2.1
  - notebook-shim=0.2.4
  - nspr=4.35
  - nss=3.100
  - numba=0.60.0
  - numcodecs=0.12.1
  - numpy=1.26.4
  - numpy_groupies=0.11.1
  - openjpeg=2.5.0
  - openssl=3.1.6
  - orc=1.9.2
  - overrides=7.7.0
  - packaging=24.1
  - pandas=2.2.2
  - pandoc=3.3
  - pandocfilters=1.5.0
  - panel=1.4.4
  - papermill=2.6.0
  - param=2.1.1
  - parso=0.8.4
  - partd=1.4.2
  - pathspec=0.12.1
  - patsy=0.5.6
  - pcre2=10.40
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=10.0.0
  - pint=0.23
  - pip=24.0
  - pixman=0.43.2
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.2.2
  - plotly=5.23.0
  - pluggy=1.5.0
  - ply=3.11
  - pooch=1.8.2
  - poppler=23.05.0
  - poppler-data=0.4.12
  - postgresql=15.4
  - proj=9.2.1
  - prometheus_client=0.20.0
  - prompt-toolkit=3.0.47
  - psutil=6.0.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pulseaudio-client=16.1
  - pure_eval=0.2.3
  - pyarrow=14.0.1
  - pyarrow-hotfix=0.6
  - pybtex=0.24.0
  - pybtex-docutils=1.0.3
  - pycparser=2.22
  - pyct=0.5.0
  - pydantic=2.8.2
  - pydantic-core=2.20.1
  - pydap=3.4.0
  - pydata-sphinx-theme=0.15.4
  - pygeos=0.14
  - pygments=2.18.0
  - pyjwt=2.8.0
  - pyparsing=3.1.2
  - pyproj=3.6.1
  - pyqt=5.15.9
  - pyqt5-sip=12.12.2
  - pyshp=2.3.1
  - pysocks=1.7.1
  - pytest=8.3.2
  - python=3.11.6
  - python-dateutil=2.9.0
  - python-eccodes=1.7.1
  - python-fastjsonschema=2.20.0
  - python-json-logger=2.0.7
  - python-tzdata=2024.1
  - python_abi=3.11
  - pytz=2024.1
  - pyviz_comms=3.0.2
  - pywavelets=1.6.0
  - pyyaml=6.0.1
  - pyzmq=26.0.3
  - qhull=2020.2
  - qt-main=5.15.8
  - rasterio=1.3.8
  - rasterstats=0.19.0
  - rav1e=0.6.6
  - rdma-core=52.0
  - re2=2023.09.01
  - readline=8.2
  - referencing=0.35.1
  - requests=2.32.3
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rioxarray=0.17.0
  - roocs-grids=0.1.2
  - roocs-utils=0.6.9
  - rpds-py=0.19.1
  - rtree=1.3.0
  - s2n=1.3.56
  - scikit-image=0.24.0
  - scikit-learn=1.5.1
  - scipy=1.14.0
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - send2trash=1.8.3
  - setuptools=71.0.4
  - shapely=2.0.1
  - simplejson=3.19.2
  - sip=6.7.12
  - six=1.16.0
  - snappy=1.1.10
  - sniffio=1.3.1
  - snowballstemmer=2.2.0
  - snuggs=1.4.7
  - sortedcontainers=2.4.0
  - soupsieve=2.5
  - sparse=0.15.4
  - sphinx=7.4.7
  - sphinx-book-theme=1.1.3
  - sphinx-comments=0.0.3
  - sphinx-copybutton=0.5.2
  - sphinx-design=0.6.0
  - sphinx-external-toc=1.0.1
  - sphinx-jupyterbook-latex=1.0.0
  - sphinx-multitoc-numbering=0.1.3
  - sphinx-thebe=0.3.1
  - sphinx-togglebutton=0.3.2
  - sphinxcontrib-applehelp=2.0.0
  - sphinxcontrib-bibtex=2.6.2
  - sphinxcontrib-devhelp=2.0.0
  - sphinxcontrib-htmlhelp=2.1.0
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=2.0.0
  - sphinxcontrib-serializinghtml=1.1.10
  - sqlalchemy=2.0.31
  - sqlite=3.46.0
  - stack_data=0.6.2
  - statsmodels=0.14.2
  - svt-av1=2.1.2
  - tabulate=0.9.0
  - tblib=3.0.0
  - tenacity=9.0.0
  - terminado=0.18.1
  - threadpoolctl=3.5.0
  - tifffile=2024.7.24
  - tiledb=2.13.2
  - tinycss2=1.3.0
  - tk=8.6.13
  - toml=0.10.2
  - tomli=2.0.1
  - toolz=0.12.1
  - tornado=6.4.1
  - tqdm=4.66.4
  - traitlets=5.14.3
  - traittypes=0.2.1
  - tree=2.1.3
  - types-python-dateutil=2.9.0.20240316
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - typing_utils=0.1.0
  - tzcode=2024a
  - tzdata=2024a
  - uc-micro-py=1.0.3
  - ucx=1.15.0
  - udunits2=2.2.28
  - uri-template=1.3.0
  - uriparser=0.9.8
  - urllib3=2.2.2
  - wcwidth=0.2.13
  - webcolors=24.6.0
  - webencodings=0.5.1
  - webob=1.8.7
  - websocket-client=1.8.0
  - wget=1.20.3
  - wheel=0.43.0
  - widgetsnbextension=4.0.11
  - wrapt=1.16.0
  - wrf-python=1.3.4.1
  - xarray=2024.6.0
  - xarray-spatial=0.4.0
  - xcb-util=0.4.0
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.0
  - xcb-util-renderutil=0.3.9
  - xcb-util-wm=0.4.1
  - xclim=0.51.0
  - xerces-c=3.2.4
  - xesmf=0.8.7
  - xkeyboard-config=2.42
  - xorg-fixesproto=5.0
  - xorg-inputproto=2.3.2
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.1
  - xorg-libsm=1.2.4
  - xorg-libx11=1.8.9
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-libxi=1.7.10
  - xorg-libxrender=0.9.11
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xf86vidmodeproto=2.3.1
  - xorg-xproto=7.0.31
  - xyzservices=2024.6.0
  - xz=5.2.6
  - yamale=5.2.1
  - yaml=0.2.5
  - yarl=1.9.4
  - zarr=2.18.2
  - zeromq=4.3.5
  - zfp=1.0.1
  - zict=3.0.0
  - zipp=3.19.2
  - zlib=1.2.13
  - zlib-ng=2.0.7
  - zstandard=0.23.0
  - zstd=1.5.6